spring.application.name=leaddesk-mini

spring.datasource.url=jdbc:postgresql://localhost:5432/LeadDesk
spring.datasource.username=postgres
spring.datasource.password=student

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}
server.port=${SERVER_PORT:8080}
server.error.include-message=never
server.error.include-stacktrace=never
